# https://docs.docker.com/compose/compose-file/

services:
    frontend:
        image: node:18-alpine
        container_name: nextjs
        ports:
            - '443:8043'
        networks:
            - front-tier
            - back-tier
        # configs:
        #     - httpd-config
        # secrets:
        #     - server-certificate

    backend:
        image: practice/nestjs
        container_name: nestjs
        # restart: always
        environment:
            TYPEORM_TYPE: 'mysql'
            TYPEORM_DATABASE: 'test'
            TYPEORM_HOST: practice.'mysql'
            TYPEORM_PORT: 3306
            TYPEORM_USERNAME: 'root'
            TYPEORM_PASSWORD: 'password'
            TYPEORM_ENABLE_SYNC: 'true'
            REDIS_HOST: practice.'redis'
            REDIS_PORT: 6379
        ports:
            - '4000:4000'
        networks:
            - back-tier
        volumes:
          - type: volume
            source: /home/hunjuly/practice/nestjs/logs
            target: /workspace/practice/logs
# 볼륨 지정하는거 이거 맞나?
volumes:
  log-data:
# configs:
#     httpd-config:
#         external: true

# secrets:
#     server-certificate:
#         external: true

networks:
    front-tier: {}
    back-tier: {}
