# https://docs.docker.com/compose/compose-file/
# build rm up/down
services:
  mysql:
    image: mysql
    container_name: practice.mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    networks:
      - vscode
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
volumes:
  mysql-data:
networks:
  vscode:
    name: vscode
    external: true
